- name: Elasticsearch service 存在確認
  sudo: yes
  shell: systemctl -a | grep elasticsearch
  register: elasticsearch_service
  failed_when: elasticsearch_service.rc not in [0, 1]

- name: Elasticsearch RPM ダウンロード
  get_url:
    url: "{{ elasticsearch_rpm_url }}"
    dest: "{{ download_path }}/{{ elasticsearch_rpm_file }}"
    timeout: 120
  when: elasticsearch_service.rc == 1

- name: Elasticsearch インストール
  sudo: yes
  yum:
    name: "{{ download_path }}/{{ elasticsearch_rpm_file }}"
    state: present
  when: elasticsearch_service.rc == 1
    
- name: /etc/elasticsearch/elasticsearch.yml の設定
  sudo: yes
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    state: present
    line: '{{ item.line }}'
  with_items:
    - line: 'configsync.config_path: /var/elasticsearch/config'
    - line: 'script.engine.groovy.inline.update: on'
  when: elasticsearch_service.rc == 1
      
- name: Elasticsearch サービス登録
  sudo: yes
  service:
    name: elasticsearch
    enabled: yes
  when: elasticsearch_service.rc == 1
    
- name: 不要なファイルの削除
  file:
    state: absent
    path: "{{ download_path }}/{{ elasticsearch_rpm_file }}"
  when: elasticsearch_service.rc == 1

  
